services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=alunos_db
      - DB_PORT=5432
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=alunos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: